# Generated by Django 5.2.9 on 2025-12-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categories',
            new_name='category',
        ),
    ]
