# Generated by Django 5.2.9 on 2025-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_categories_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
