# Generated by Django 5.2.9 on 2025-12-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to='moments'),
        ),
    ]
